version : '3.7'

services:
    cook:
        build:
            context: ./server
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                OVERCOOKED_BRANCH: "${OVERCOOKED_BRANCH:-master}"
                HARL_BRANCH: "${HARL_BRANCH:-master}"
                #GRAPHICS: "${GRAPHICS:-overcooked_graphics_v2.2.js}"
        environment: 
            FLASK_ENV: "${BUILD_ENV:-production}"
        ports:
            - 8080:8080

    nginx:
        build:
            context: ./nginx
            args:
                NGINX_CONF: ${NGINX_CONF}
        volumes:
            - ${STATIC_FOLDER}:/var/cook/static/:ro
        ports:
            - 80:80
        depends_on:
            - cook